// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PdfExportSample.Data;

#nullable disable

namespace PdfExportSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502052208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PdfExportSample.Model.PatientData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceAmountCollected")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CCN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CoPaymentAddition")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateOfAdmission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfDischarge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageRate")
                        .HasColumnType("integer");

                    b.Property<string>("PreauthId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surgery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TPAName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientTable");
                });
#pragma warning restore 612, 618
        }
    }
}
